language: generic

sudo: false

jobs:
  include:
    - name: Common
      env:
        - JAVA_OPTS="-XX:MaxPermSize=1024m -XX:+CMSClassUnloadingEnabled -XX:+HeapDumpOnOutOfMemoryError -Xmx2048m"
      language: android
      dist: trusty
      components:
        - tools
        - platform-tools
        - extra-android-m2repository
      before_install:
        - yes | sdkmanager "platforms;android-28"
        - yes | sdkmanager "build-tools;28.0.3"
      licenses:
        - 'android-sdk-preview-license-52d11cd2'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
      before_script:
        - chmod +x gradlew
        - chmod +x gradle/wrapper/gradle-wrapper.jar
      script:
        - ./gradlew test jvmTest ktlintCheck --parallel
    - name: iOS
      language: swift
      before_cache:
        - brew cleanup
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
      before_script:
        - brew install swiftlint
        - cd ios
      script: swiftlint --strict
